# APPLICATION
spring.application.name=securechat-backend
server.port=8080

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/securechat_db
spring.datasource.username=securechat_user
spring.datasource.password=securechat_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# FLYWAY
spring.flyway.enabled=true
spring.flyway.clean-disabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=SecureChatSuperSecretKey_ChangeThis!
jwt.expiration=86400000
